### ISSUE TITLE
Still can't see grunt tasks sometimes when I change between projects

### ISSUE THREAD

**Issue by mascardoso** [tvooo/sublime-grunt#69]
Hi I keep having this error.

Traceback (most recent call last):
  File ".\sublime_plugin.py", line 339, in run_
    return self.run()
  File ".\main.py", line 132, in run
  File ".\main.py", line 16, in **init**
  File ".\main.py", line 80, in list_gruntfiles
  File ".\main.py", line 90, in choose_file
TypeError: No registered converter was able to produce a C++ rvalue of type class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > from this Python object of type list

Was this already fixed?

Thanks

**Comment by tvooo** [comment]
Repository was moved to https://github.com/sptndc/sublime-grunt
Please re-file any issues that still exist.
